// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkateboardApi.Models;

#nullable disable

namespace SkateboardTracker.Migrations
{
    [DbContext(typeof(SkateboardApiContext))]
    [Migration("20231105203856_AddInitial")]
    partial class AddInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SkateboardApi.Models.Trick", b =>
                {
                    b.Property<int>("TrickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<bool>("OnLock")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("TrickId");

                    b.ToTable("Tricks");

                    b.HasData(
                        new
                        {
                            TrickId = 1,
                            Description = "backside 360 pop shove-it with kickflip",
                            Location = "Stronger skatepark, street area, flatland",
                            Name = "Treflip",
                            Notes = "siiick",
                            OnLock = true
                        },
                        new
                        {
                            TrickId = 2,
                            Description = "nose ollie",
                            Location = "skatepark 4 stair",
                            Name = "Nollie",
                            Notes = "bail",
                            OnLock = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
